version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=investment_tracker_test
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.arm
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=testing
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/investment_tracker_test
      - SECRET_KEY=test-secret-key
      - JWT_SECRET_KEY=test-jwt-secret
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: pytest tests/ -v