version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=investment_tracker
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio_network

  # Redis for Celery
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - portfolio_network

  # Flask Backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/investment_tracker
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./data:/app/data
    networks:
      - portfolio_network

  # Frontend Nginx Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # This is the correct port mapping for production
    depends_on:
      - backend
    networks:
      - portfolio_network

# Docker Networks
networks:
  portfolio_network:
    driver: bridge

# Docker Volumes
volumes:
  postgres_data:
  redis_data:
